### PR TITLE
camel cased JSON requests and responses

### PR DESCRIPTION
**Pull request by xinitrc86**
Added usage of /ui2/cl_json to convert from/to camel cased JSON bodies.

### CODE REVIEW

**Comment by larshp** [comment]
what is the expected behavior regarding backwards compatibility?

**Comment by xinitrc86** [comment]
Inbound body is expected to be camel cased JSON, same as outbound. 
I'm not sure how the transformation worked for the response, but if it adds "{DATA:" to i...that is lost. 
The serializer offers different options. We could add them to the meta maybe?
                  none,          
                  low_case,   
                  camel_case,
                  extended

**Comment by larshp** [comment]
yea, the change should not break all existing installations

**Comment by larshp** [comment]
should not break all existing installations

**Pull request closed without merging**
