### PR TITLE
Add possibility to use tag descriptions

### LINKED ISSUE #28: tags, support for descriptions
will require new structure instead of the currently used RT_META

### PR DESCRIPTION
**Pull request by BlackmanCC**
Fixes #28 
Tag descriptions can be added with method zcl_swag~set_tagdescription.

The use of externaldocs is optional.

### CODE REVIEW

**Review by BlackmanCC — COMMENTED** [review]
@larshp I do not understand why abaplint shows a problem with method length. can you help?

**Comment by BlackmanCC** [comment]
@larshp sorry, but I cannot find a Indentation problem. abaplint says
"Reduce method length to max 160 statements, currently 161"

**Comment by larshp** [comment]
its the number of statments in the method, suggest extracting some part of the method to a new method

**Comment by BlackmanCC** [comment]
> its the number of statments in the method, suggest extracting some part of the method to a new method

@larshp  all methods in zcl_swag have far less than 160 lines. the message must be an error.

**Comment by larshp** [comment]
the macros might count twice, one for the macro call and one for the statement inside the macro

**Comment by BlackmanCC** [comment]
> the macros might count twice, one for the macro call and one for the statement inside the macro

@larshp which method has problem? do you have any recommendations for change or fix?

**Comment by larshp** [comment]
image

**Comment by larshp** [comment]
cool

there might be a bug, I've opened https://github.com/abaplint/abaplint/issues/1572

on long term I'd like to get rid of the macros

**Comment by BlackmanCC** [comment]
> cool
> 
> there might be a bug, I've opened [abaplint/abaplint#1572](https://github.com/abaplint/abaplint/issues/1572)
> 
> on long term I'd like to get rid of the macros

yeah, I also thought about killing the macro and substitute it by a method call, but in the current situtation a macro fits best, even I  do not like macros ;-)

**Comment by larshp** [comment]
the whole JSON concatenation/build should be replaced with a class representing the JSON, sometime in the future...

I'll review the pull requests sometime, but its not at the top of my list this week...

**Comment by BlackmanCC** [comment]
> the whole JSON concatenation/build should be replaced with a class representing the JSON, sometime in the future...
> 
> I'll review the pull requests sometime, but its not at the top of my list this week...

sounds good but do not understand what you mean, IU think it works now. take your time for review and let me know if you suggest any changes.

**Comment by BlackmanCC** [comment]
@larshp I hope you can check the requests... THX

**Comment by BlackmanCC** [comment]
@larshp Please also merge thios pull request

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
